version: "3"
services:
  app:
    image: hormold/gmail-bot:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "6000:3000"
    env_file: .env
    environment:
      - DB_URL=mongodb://mongo:27017/myapp
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 90 --label-enable --cleanup

volumes:
  mongo-data:
