version: "3"
services:
  app:
    build: .
    ports:
      - "6000:3000"
    env_file: .env
    environment:
      - DB_URL=mongodb://mongo:27017/myapp
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
